language: c
sudo: required

compiler:
- gcc

addons:
  apt:
    packages:
      - gcc
      - cmake
      - pkg-config
      - openssl
      - zlib1g-dev
  
script:
- ./build_release.sh

branches:
    only:
    - master
