#ifndef UNKNOWNECHO_RELAY_MESSAGE_ID_H
#define UNKNOWNECHO_RELAY_MESSAGE_ID_H

#include <unknownecho/bool.h>

typedef enum {
    UNKNOWNECHO_RELAY_MESSAGE_ID_ESTABLISH = 0,
    UNKNOWNECHO_RELAY_MESSAGE_ID_DISCONNECT,
    UNKNOWNECHO_RELAY_MESSAGE_ID_SEND,
    UNKNOWNECHO_RELAY_MESSAGE_ID_RELAY,
    UNKNOWNECHO_RELAY_MESSAGE_ID_RECEIVE,
    UNKNOWNECHO_RELAY_MESSAGE_ID_SEND_ACK,
    UNKNOWNECHO_RELAY_MESSAGE_ID_RECEIVE_ACK
} ue_relay_message_id;

bool ue_relay_message_id_is_valid(int id);

#endif
