#ifndef UNKNOWNECHO_SOCKET_CHANNEL_MESSAGE_TYPE_H
#define UNKNOWNECHO_SOCKET_CHANNEL_MESSAGE_TYPE_H

typedef enum {
    CHANNEL_KEY_REQUEST         = 1,
    DISCONNECTION_NOW_REQUEST   = 2,
    SHUTDOWN_NOW_REQUEST        = 3,
    CHANNEL_CONNECTION_REQUEST  = 4,
    GET_CERTIFICATE_REQUEST     = 5,
    NICKNAME_REQUEST            = 6,
    CHANNEL_KEY_REQUEST_ANSWER  = 7,
    CHANNEL_CONNECTION_RESPONSE = 8,
    CHANNEL_KEY_RESPONSE        = 9,
    CHANNEL_KEY_CREATOR_STATE   = 10,
    WAIT_CHANNEL_KEY_STATE      = 11,
    MESSAGE                     = 12,
    CSR_TLS_REQUEST             = 13,
    CSR_CIPHER_REQUEST          = 14,
    CSR_SIGNER_REQUEST          = 15,
    CERTIFICATE_RESPONSE        = 16,
    NICKNAME_RESPONSE           = 17,
    CSR_TLS_RESPONSE            = 18,
    CSR_CIPHER_RESPONSE         = 19,
    CSR_SIGNER_RESPONSE         = 20,
    ALREADY_CONNECTED_RESPONSE  = 21
} ue_socket_channel_message_type;

#endif
