#
##
add_library(@LIB_NAME@ ${@LIB_NAME@_LIB_TYPE} IMPORTED)
set_target_properties(@LIB_NAME@ PROPERTIES
  IMPORTED_LOCATION             "${@LIB_NAME@_LOCATION}"
  INTERFACE_LINK_LIBRARIES      "${@LIB_NAME@_LIBRARIES}"
  INTERFACE_COMPILE_DEFINITIONS "${@LIB_NAME@_DEFINITIONS}"
  INTERFACE_INCLUDE_DIRECTORIES "${@LIB_NAME@_INCLUDE_DIRS}"
  INTERFACE_LINK_DIRECTORIES    "${@LIB_NAME@_DIRECTORIES}"
)

