#
## LIB VARS
set(@LIB_NAME@_LIBRARY_@LIBRARY_ONCE_TYPE@ "$<TARGET_LINKER_FILE_NAME:@LIBRARY_ONCE@>")

#
##
set(@LIB_NAME@_LIB_TYPE @LIBRARY_ONCE_TYPE@)
set(@LIB_NAME@_LIBRARIES "${@LIB_NAME@_ROOT_DIR}/lib/${@LIB_NAME@_LIBRARY_@LIBRARY_ONCE_TYPE@}")
set(@LIB_NAME@_LIBRARY   "${@LIB_NAME@_LIBRARIES}")

